---
- name: install gitric
  pip: name=gitric state=present

- name: install fabric
  pip: name=fabric state=present

- name: install httpie
  pip: name=httpie state=present

- name: install stormssh
  pip: name=stormssh state=present

- name: install raven (sentry client)
  pip: name=raven state=present
